extends CharacterBody2D

const SPEED := 200
const INTERACT_RANGE := 120.0

# AI-generated: this function code was generated by Claude
func _physics_process(delta): 
	var input_vector = Vector2.ZERO

	if Input.is_action_pressed("move_right"):
		input_vector.x += 1
	if Input.is_action_pressed("move_left"):
		input_vector.x -= 1
	if Input.is_action_pressed("move_down"):
		input_vector.y += 1
	if Input.is_action_pressed("move_up"):
		input_vector.y -= 1
		

	input_vector = input_vector.normalized()  # AI-generated: this line of code was generated by Claude
	velocity = input_vector * SPEED  # AI-generated: this line of code was generated by Claude
	move_and_slide()  # AI-generated: this line of code was generated by Claude
