extends TileMapLayer

const WIDTH: int = 60 
const HEIGHT: int = 40

const TILE_GRASS: int = 0   # AI-generated: this line of code was generated by Claude
const TILE_DIRT: int = 1    # AI-generated: this line of code was generated by Claude

var all_tiles: Array[int] = [TILE_GRASS, TILE_DIRT]  # AI-generated: this line of code was generated by Claude

var grid: Array = []  # AI-generated: this line of code was generated by Claude


func _ready() -> void:
	print("WFC READY")   # AI-generated: this line of code was generated by Claude
	generate_map()       # AI-generated: this line of code was generated by Claude


func generate_map() -> void: 
	clear()
	_init_grid() 

	var attempts: int = 0  # AI-generated: this line of code was generated by Claude
	while attempts < 20:   # AI-generated: this line of code was generated by Claude
		if _run_wfc():
			_draw_result()  # AI-generated: this line of code was generated by Claude
			return
		attempts += 1  # AI-generated: this line of code was generated by Claude
		_init_grid()

	print("WFC failed after 20 attempts.")

# AI-generated: this function code was generated by Claude
func _init_grid() -> void:
	
	grid.clear()
	for x in range(WIDTH):
		var col: Array = []
		print(x)
		for y in range(HEIGHT):
			print(y)
			col.append(all_tiles.duplicate())    # Start with both tiles available
		grid.append(col)

# AI-generated: this function code was generated by Claude
func _run_wfc() -> bool:
	while true:
		var cell := _find_lowest_entropy_cell()

		if cell == Vector2i(-1, -1):
		
			for x in range(WIDTH):
				for y in range(HEIGHT):
					if (grid[x][y] as Array).size() != 1:
						return false
			return true

		var x := cell.x
		var y := cell.y
		var opts: Array = grid[x][y] as Array

		if opts.is_empty():
			return false

		var choice: int = opts[randi() % opts.size()]
		grid[x][y] = [choice]

		if not _propagate_from(x, y):
			return false

	return false  

# AI-generated: this function code was generated by Claude
func _find_lowest_entropy_cell() -> Vector2i:
	var best_entropy := 999
	var best := Vector2i(-1, -1)

	for x in range(WIDTH):
		for y in range(HEIGHT):
			var poss: Array = grid[x][y] as Array
			var entropy: int = poss.size()

			if entropy > 1 and entropy < best_entropy:
				best_entropy = entropy
				best = Vector2i(x, y)

	return best


func _propagate_from(sx: int, sy: int) -> bool:
	var queue: Array[Vector2i] = [Vector2i(sx, sy)] # AI-generated: this line of code was generated by Claude

	while queue.size() > 0:
		var c: Vector2i = queue.pop_front() # AI-generated: this line of code was generated by Claude

		for dir in ["up", "down", "left", "right"]: # AI-generated: this line of code was generated by Claude
			var nx := c.x 
			var ny := c.y

			match dir: # AI-generated: this line of code was generated by Claude
				"up": ny -= 1
				"down": ny += 1
				"left": nx -= 1
				"right": nx += 1

			if nx < 0 or nx >= WIDTH or ny < 0 or ny >= HEIGHT: # AI-generated: this line of code was generated by Claude
				continue # AI-generated: this line of code was generated by Claude

			if _prune_neighbor(c.x, c.y, nx, ny, dir): # AI-generated: this line of code was generated by Claude
				var neighbor_list: Array = grid[nx][ny] as Array # AI-generated: this line of code was generated by Claude
				if neighbor_list.is_empty():
					return false # AI-generated: this line of code was generated by Claude
				queue.append(Vector2i(nx, ny))

	return true


func _allowed_neighbors(id: int, dir: String) -> Array[int]:

	return [TILE_GRASS, TILE_DIRT] # AI-generated: this line of code was generated by Claude

# AI-generated: this function code was generated by Claude
func _prune_neighbor(x: int, y: int, nx: int, ny: int, dir: String) -> bool:
	var changed := false

	var source: Array = grid[x][y] as Array 
	var neighbor: Array = grid[nx][ny] as Array

	var allowed := {}

	for s in source:
		for t in _allowed_neighbors(int(s), dir):
			allowed[t] = true

	var new_list: Array = []
	for tile in neighbor:
		if allowed.has(int(tile)):
			new_list.append(tile)

	if new_list.size() < neighbor.size():
		grid[nx][ny] = new_list
		changed = true

	return changed

# AI-generated: this function code was generated by Claude
func _draw_result() -> void:
	print("DRAW RESULT")
	for x in range(WIDTH):
		for y in range(HEIGHT):
			var tile_list: Array = grid[x][y] as Array
			var tile_id: int = int(tile_list[0])

			set_cell(Vector2i(x, y), tile_id, Vector2i(0, 0))

			print("Placed tile", tile_id, "at", x, y)
