const net = require("net");
const client = new net.Socket();

client.connect(9000, "127.0.0.1", () => { // AI-generated: this line of code was generated by Claude
    console.log("CiF Processor connected.");
    client.write("CIF\n");  // AI-generated: this line of code was generated by Claude
});


client.on("data", (data) => { // AI-generated: this line of code was generated by Claude
    const msg = data.toString().trim(); // AI-generated: this line of code was generated by Claude
    console.log("CiF received:", msg);

    if (msg.startsWith("INTERACT")) { 
        const npc_id = parseInt(msg.split(":")[1]); 


        const social_state = {  // AI-generated: this line of code was generated by Claude
            npc: npc_id,    // AI-generated: this line of code was generated by Claude
            mood: ["happy", "angry", "neutral", "curious"][npc_id % 4],       // AI-generated: this line of code was generated by Claude
            trust: Math.floor(Math.random() * 100)      // AI-generated: this line of code was generated by Claude
        };

        client.write(JSON.stringify(social_state) + "\n");
        console.log("CiF sent:", social_state);  // AI-generated: this line of code was generated by Claude
    }
});
