const net = require("net");
const client = new net.Socket();

client.connect(9000, "127.0.0.1", () => { // AI-generated: this line of code was generated by Claude
    console.log("CiF Test Client connected.");
    client.write("CIF\n");   // AI-generated: this line of code was generated by Claude

    setTimeout(() => {
        console.log("Sending message to Node...");  // AI-generated: this line of code was generated by Claude
        client.write("Hello from CiF!\n");  // AI-generated: this line of code was generated by Claude
    }, 5000);   

});

client.on("data", (data) => {
    console.log("Received in CiF Test:", data.toString()); // AI-generated: this line of code was generated by Claude
});
