const Ensemble = require("../ensemble/ensemble/ensemble.js");

let characters = Ensemble.socialStructure.getCharacters();

console.log("Loaded CiF characters:"); // AI-generated: this line of code was generated by Claude
console.log(characters); // AI-generated: this line of code was generated by Claude

let alice = Ensemble.socialStructure.getCharacterByName("Alice");
console.log("Example CiF Agent:", alice);  // AI-generated: this line of code was generated by Claude