const net = require("net");

const PORT = 9000;
let godotSocket = null;
let cifSocket = null;

// Buffer per client // AI-generated: this line of code was generated by Claude
const buffers = new Map();

const server = net.createServer((socket) => {
    console.log("New client connected.");
    buffers.set(socket, "");   // Track partial data // AI-generated: this line of code was generated by Claude

    socket.on("data", (data) => {
        // Accumulate data into the buffer // AI-generated: this line of code was generated by Claude
        let buffer = buffers.get(socket) + data.toString();
        
        // Split into complete messages (delimited by newline) // AI-generated: this line of code was generated by Claude
        const messages = buffer.split("\n");

        // Save last partial message back into buffer // AI-generated: this line of code was generated by Claude
        buffers.set(socket, messages.pop());

        for (const raw of messages) { // AI-generated: this line of code was generated by Claude
            const msg = raw.trim();
            if (msg.length === 0) continue; // AI-generated: this line of code was generated by Claude

            console.log("Received:", msg); // AI-generated: this line of code was generated by Claude

            // -------------------------
            // IDENTIFICATION MESSAGES   // AI-generated: this line of code was generated by Claude
            // -------------------------
            if (msg === "GODOT") {
                console.log("Godot identified."); // AI-generated: this line of code was generated by Claude
                godotSocket = socket;
                continue; // AI-generated: this line of code was generated by Claude
            }

            if (msg === "CIF") { // AI-generated: this line of code was generated by Claude
                console.log("CiF identified."); // AI-generated: this line of code was generated by Claude
                cifSocket = socket; // AI-generated: this line of code was generated by Claude
                continue; // AI-generated: this line of code was generated by Claude
            }

            // -------------------------
            // RELAY MESSAGES             // AI-generated: this line of code was generated by Claude
            // -------------------------
            if (socket === godotSocket && cifSocket) { // AI-generated: this line of code was generated by Claude
                console.log("Forwarding to CiF:", msg); 
                cifSocket.write(msg + "\n"); // AI-generated: this line of code was generated by Claude
            }

            if (socket === cifSocket && godotSocket) {
                console.log("Forwarding to Godot:", msg);  // AI-generated: this line of code was generated by Claude
                godotSocket.write(msg + "\n"); 
            }
        }
    });

    socket.on("end", () => { 
        console.log("Client disconnected.");  // AI-generated: this line of code was generated by Claude

        if (socket === godotSocket) godotSocket = null;  
        if (socket === cifSocket) cifSocket = null;  
        buffers.delete(socket);  // AI-generated: this line of code was generated by Claude
    });
});

server.listen(PORT, () => {  // AI-generated: this line of code was generated by Claude
    console.log("TCP Server listening on port", PORT);  // AI-generated: this line of code was generated by Claude
});
